apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: segundo-pod
    #Pode por qualquer chave com qualquer valor
spec:
  containers:
  - name: container-pod-2
    image: nginx:latest
    ports: 
      - containerPort: 80
