#Serviço do pod 2
apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec:
  type: NodePort
  selector: 
    app: primeiro-pod 
    #Seleciona quem tem essa chave-valor
  ports:
    - port: 80
      nodePort: 30000



